baseURL = "https://flak153.github.io/BlueGlass.nyc/"

languageCode = "en-us"
publishDir = "docs"
title = "BlueGlass | Modern Web Development"
theme = "meghna"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

#    [[menu.nav]]
#    name = "Portfolio"
#    URL = "portfolio"
#    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

  #  [[menu.nav]]
  #  name = "Pricing"
  #  URL = "pricing"
  #  weight = 6

  #  [[menu.nav]]
  #  name = "Blog"
  #  URL = "blog"
  #  weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]
custom_js = ["js/custom.js"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "How will you stay ahead in an automated world?"
    content= "The machines are here to stay. Don't let your business fall behind the curve.  "
    btn = true
    btnText="Explore Us"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = false
    title = "Fast & Flexible Service"
    content = "We are a full service consultancy, providing end-to-end project management for our clients"
    btnURL = "/#contact-us"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = false
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "320"

        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "565"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"
    
    # footer
    [params.footer]
        copyright = "AckFin Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "#"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "#"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        url = "#"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "#"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "#"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        url = "#"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
